import { routes } from "./routes";

/** Служебные слова, которые пользователь не может занять как адрес своей страницы. */
const reservedWords = [
  "about",
  "account",
  "accounts",
  "admin",
  "administrator",
  "api",
  "app",
  "apps",
  "assets",
  "auth",
  "blog",
  "callback",
  "contact",
  "contacts",
  "dashboard",
  // Адрес демо-профиля
  "demo",
  "docs",
  "edit",
  "email",
  "explore",
  "faq",
  "favicon",
  "feed",
  "freud",
  "freudin",
  "help",
  "home",
  "images",
  "img",
  "index",
  "info",
  "legal",
  "login",
  "logout",
  "mail",
  "manifest",
  "me",
  "new",
  "news",
  "null",
  "oauth",
  "official",
  "onboarding",
  "opengraph-image",
  "privacy",
  "profile",
  "profiles",
  "register",
  "robots",
  "root",
  "search",
  "security",
  "settings",
  "signin",
  "signout",
  "signup",
  "sitemap",
  "static",
  "status",
  "support",
  "system",
  "team",
  "terms",
  "test",
  "twitter-image",
  "undefined",
  "user",
  "users",
  "www",
];

/** Первые сегменты путей страниц (`/login` → `login`): новые роуты попадают сюда автоматически. */
const routeSegments = Object.values(routes).flatMap((route) =>
  typeof route === "string" && route !== "/" ? [route.split("/")[1]] : [],
);

export const reservedUsernames: ReadonlySet<string> = new Set([...reservedWords, ...routeSegments]);
